spring.datasource.url=jdbc:postgresql://ep-noisy-bar-apyuct35-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_TiYnH6VckL4g&sslmode=require&channel_binding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true